In [1]:
data = [['1' , '1' , 'Olivos' , 'Esteban Echeverria 2870' , 'Munro' , '4756-2360' , '1' , 'A' , '1' , 'None' , 'Buenos Aires' , '1605' , 'None' , 'None' , 'None' , 'None' , 'B' , 'None' , 'None' , 'None' , 'None' , 'None' , '1999-01-18 12:59:16' , '1' , '1988-03-03 00:00:00' , '1' , '1' , 'None' , '7796613000010' , 'None' , 'R1' , '3' , 'Olivo' , '1' , '1' , '0'],
            ['1' , '1' , 'Olivos' , 'Esteban Echeverria 2870' , 'Munro' , '4756-2360' , '1' , 'A' , '1' , 'None' , 'Buenos Aires' , '1605' , 'None' , 'None' , 'None' , 'None' , 'B' , 'None' , 'None' , 'None' , 'None' , 'None' , '1999-01-18 12:59:16' , '1' , '1988-03-03 00:00:00' , '1' , '1' , 'None' , '7796613000010' , 'None' , 'R1' , '3' , 'Olivo' , '1' , '1' , '0'],
            ['1' , '1' , 'Olivos' , 'Esteban Echeverria 2870' , 'Munro' , '4756-2360' , '1' , 'A' , '1' , 'None' , 'Buenos Aires' , '1605' , 'None' , 'None' , 'None' , 'None' , 'B' , 'None' , 'None' , 'None' , 'None' , 'None' , '1999-01-18 12:59:16' , '1' , '1988-03-03 00:00:00' , '1' , '1' , 'None' , '7796613000010' , 'None' , 'R1' , '3' , 'Olivo' , '1' , '1' , '0']
            ]

In [2]:
print(data)

[['1', '1', 'Olivos', 'Esteban Echeverria 2870', 'Munro', '4756-2360', '1', 'A', '1', 'None', 'Buenos Aires', '1605', 'None', 'None', 'None', 'None', 'B', 'None', 'None', 'None', 'None', 'None', '1999-01-18 12:59:16', '1', '1988-03-03 00:00:00', '1', '1', 'None', '7796613000010', 'None', 'R1', '3', 'Olivo', '1', '1', '0'], ['1', '1', 'Olivos', 'Esteban Echeverria 2870', 'Munro', '4756-2360', '1', 'A', '1', 'None', 'Buenos Aires', '1605', 'None', 'None', 'None', 'None', 'B', 'None', 'None', 'None', 'None', 'None', '1999-01-18 12:59:16', '1', '1988-03-03 00:00:00', '1', '1', 'None', '7796613000010', 'None', 'R1', '3', 'Olivo', '1', '1', '0'], ['1', '1', 'Olivos', 'Esteban Echeverria 2870', 'Munro', '4756-2360', '1', 'A', '1', 'None', 'Buenos Aires', '1605', 'None', 'None', 'None', 'None', 'B', 'None', 'None', 'None', 'None', 'None', '1999-01-18 12:59:16', '1', '1988-03-03 00:00:00', '1', '1', 'None', '7796613000010', 'None', 'R1', '3', 'Olivo', '1', '1', '0']]


In [37]:
import numpy as np
b=np.array([(1,2,3),(4,5,6)])
print(b)


arraylist =[(1526869384.273246, 0, 'a0'),
(1526869385.273246, 1, 'a1'),
(1526869386.273246, 2, 'a2'),
(1526869387.273246, 3, 'a3'),
(1526869388.273246, 4, 'a4'),
(1526869389.273246, 5, 'a5'),
(1526869390.273246, 6, 'a6'),
(1526869391.273246, 7, 'a7'),
(1526869392.273246, 8, 'a8'),
(1526869393.273246, 9, 'a9'),
(1526869384.273246, 0, 'a0'),
(1526869385.273246, 1, 'a1'),
(1526869386.273246, 2, 'a2'),
(1526869387.273246, 3, 'a3'),
(1526869388.273246, 4, 'a4'),
(1526869389.273246, 5, 'a5'),
(1526869390.273246, 6, 'a6'),
(1526869391.273246, 7, 'a7'),
(1526869392.273246, 8, 'a8'),
(1526869393.273246, 9, 'a9')]

dtype = [('A', 'float'), ('B', 'int'), ('C', '<U32')]
array = np.array(arraylist, dtype=dtype)

array['A'].dtype


dtype2=[('A', 'int'), ('B', 'int'), ('C', '<U32'),('D', '<U32'), ('E', '<U32'), ('F', '<U32'), ('G', 'int')]

[[1 2 3]
 [4 5 6]]


In [33]:
c = np.arange(24).reshape(2,3,4) 
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [34]:
a = np.arange(10)**3

In [35]:
print(a)
np.datetime64(np.datetime64(datetime.datetime.now()).astype(long), 'us')
dataReg = [[1, 1, 'Olivos', 'Esteban Echeverria 2870', 'Munro', '4756-2360', 1,'1988-03-03 00:00:00'], 
           [1, 2, 'Olivos', 'Patricia Bonaldy 9999'  , 'Munro', '4756-5555', 1,'1987-03-17 00:00:00']
          ]


[  0   1   8  27  64 125 216 343 512 729]


NameError: name 'datetime' is not defined

In [60]:
import numpy as np

dtype = [('A', 'int'), ('B', '<U32'), ('C', '<U32'), ('D', '<U32'), ('E', '<U32'),('F', 'int'), ('G', 'datetime64[ms]')]
dataReg1 = [(1, 'Olivos','Esteban Echeverria 2870','4756-2360','Munro',1,'1988-03-03')]

array2 = np.array(dataReg1, dtype=dtype)
array2['G'].dtype

print(array2)

[(1, 'Olivos', 'Esteban Echeverria 2870', '4756-2360', 'Munro', 1, '1988-03-03T00:00:00.000')]


ValueError: invalid literal for int() with base 10: 'Olivos'